### ISSUE TITLE
help

### ISSUE THREAD

**Issue by rara111** [Mikyan0207/TwitCasting.Net.Downloader#1]
> http://ka.do/CKDG

I would like to download this recording
I'm a beginner so I don't know anything T^T
I tried as written
Even if it was not this recording, only an error occurred

please Thank you!

-------------------------------
Kochira no rokuga o download shitaidesuga shoshinsha nanode nani mo wakaranai T ^ T
kaitearu touri yatte mitakedo
kono rokuga janakute mo error shika denakattadesu douka onegaishimasu!

**Comment by Mikyan0207** [comment]
Unfortunately, as far as I know it is impossible to download a paid video. If I find a solution I will implement it but it is not possible at the moment.
